name: Ingest Chat Output
on:
  issue_comment:
    types: [created]

permissions:
  contents: write
  pull-requests: write

jobs:
  ingest:
    if: startsWith(github.event.comment.body, '/ingest')
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Run ingest script on comment body
        env:
          COMMENT_BODY: ${{ github.event.comment.body }}
        run: |
          node tools/ingest-chat.js <<'EOF'
          $COMMENT_BODY
          EOF

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v6
        with:
          commit-message: "ingest: apply chat output"
          branch: ingest/${{ github.run_id }}
          title: "Ingest chat output (${{ github.run_id }})"
          body: "Automated PR created from /ingest on issue #${{ github.event.issue.number }}"
